package id.semantics.soya.vocab;/* CVS $Id: $ */

import org.apache.jena.rdf.model.*;

/**
 * Vocabulary definitions from ../dpvo-05-lite.ttl
 * @author Auto-generated by schemagen on 10 Apr 2022 17:14
 */
public class DPVO {
    /** <p>The RDF model that holds the vocabulary terms</p> */
    private static final Model M_MODEL = ModelFactory.createDefaultModel();

    /** <p>The namespace of the vocabulary as a string</p> */
    public static final String NS = "https://w3id.org/dpv/dpv-owl#";

    /** <p>The namespace of the vocabulary as a string</p>
     * @return namespace as String
     * @see #NS */
    public static String getURI() {return NS;}

    /** <p>The namespace of the vocabulary as a resource</p> */
    public static final Resource NAMESPACE = M_MODEL.createResource( NS );

    /** <p>The ontology's owl:versionInfo as a string</p> */
    public static final String VERSION_INFO = "0.5";

    /** <p>The actual notice that the Data Subject received to consent to, either a text
     *  or link to a document, which should be usable to decide whether the form or
     *  consent was compliant to legislation, e.g. documenting how the user has been
     *  informed about rights and implications (such as, right to data portability,right
     *  to recitffy, right to erasure, right to restrict processing, right to object,
     *  rights regarding automated decision making or profiling, processors, third
     *  parties, sub-processors, outside-EEA transfers, automated decision-making,
     *  or other necessary details of the privacy-policy). Can be TextOrDocumentOrURI.</p>
     */
    public static final Property HAS_CONSENT_NOTICE = M_MODEL.createProperty( "https://w3id.org/dpv/dpv-owl#hasConsentNotice" );

    /** <p>parent property for controller, processor, data subject, authority, etc.?</p> */
    public static final Property HAS_ENTITY = M_MODEL.createProperty( "https://w3id.org/dpv/dpv-owl#hasEntity" );

    public static final Property HAS_EXPIRY = M_MODEL.createProperty( "https://w3id.org/dpv/dpv-owl#hasExpiry" );

    public static final Property HAS_EXPIRY_TIME = M_MODEL.createProperty( "https://w3id.org/dpv/dpv-owl#hasExpiryTime" );

    public static final Property HAS_LEGAL_BASIS = M_MODEL.createProperty( "https://w3id.org/dpv/dpv-owl#hasLegalBasis" );

    public static final Property HAS_LOCATION = M_MODEL.createProperty( "https://w3id.org/dpv/dpv-owl#hasLocation" );

    public static final Property HAS_ORGANISATIONAL_MEASURE = M_MODEL.createProperty( "https://w3id.org/dpv/dpv-owl#hasOrganisationalMeasure" );

    public static final Property HAS_PERSONAL_DATA = M_MODEL.createProperty( "https://w3id.org/dpv/dpv-owl#hasPersonalData" );

    public static final Property HAS_PROCESSING = M_MODEL.createProperty( "https://w3id.org/dpv/dpv-owl#hasProcessing" );

    /** <p>This field can be used to proivde a justification why the provision was provided
     *  by another DataSubject or legal entity, e.g. declariing the relationship (parent,
     *  guardian), in combination with the field provisionBy</p>
     */
    public static final Property HAS_PROVISION_BY_JUSTIFICATION = M_MODEL.createProperty( "https://w3id.org/dpv/dpv-owl#hasProvisionByJustification" );

    /** <p>Can be used to record information of how consent was provided e.g. by a click
     *  to a form, in writing, etc., by logging into a system and confirm per email,
     *  or with some additional authentication, etc.</p>
     */
    public static final Property HAS_PROVISION_METHOD = M_MODEL.createProperty( "https://w3id.org/dpv/dpv-owl#hasProvisionMethod" );

    public static final Property HAS_PROVISION_TIME = M_MODEL.createProperty( "https://w3id.org/dpv/dpv-owl#hasProvisionTime" );

    public static final Property HAS_PURPOSE = M_MODEL.createProperty( "https://w3id.org/dpv/dpv-owl#hasPurpose" );

    public static final Property HAS_RECIPIENT = M_MODEL.createProperty( "https://w3id.org/dpv/dpv-owl#hasRecipient" );

    public static final Property HAS_RISK = M_MODEL.createProperty( "https://w3id.org/dpv/dpv-owl#hasRisk" );

    public static final Property HAS_TECHNICAL_MEASURE = M_MODEL.createProperty( "https://w3id.org/dpv/dpv-owl#hasTechnicalMeasure" );

    public static final Property HAS_TECHNICAL_ORGANISATIONAL_MEASURE = M_MODEL.createProperty( "https://w3id.org/dpv/dpv-owl#hasTechnicalOrganisationalMeasure" );

    /** <p>This field can be used to proivde a justification why the weithdrawal was
     *  done by another DataSubject or legal entity, e.g. declariing the relationship
     *  (parent, guardian), in combination with the field withdrawalBy</p>
     */
    public static final Property HAS_WITHDRAWAL_BY_JUSTIFICATION = M_MODEL.createProperty( "https://w3id.org/dpv/dpv-owl#hasWithdrawalByJustification" );

    /** <p>Can be used to record information of how to withdraw consent, e.g. by a click
     *  to a form, in writing, etc., by logging into a system and confirm per email,
     *  or with some additional authentication, etc.</p>
     */
    public static final Property HAS_WITHDRAWAL_METHOD = M_MODEL.createProperty( "https://w3id.org/dpv/dpv-owl#hasWithdrawalMethod" );

    public static final Property HAS_WITHDRAWAL_TIME = M_MODEL.createProperty( "https://w3id.org/dpv/dpv-owl#hasWithdrawalTime" );

    public static final Resource ACADEMIC_RESEARCH = M_MODEL.createResource( "https://w3id.org/dpv/dpv-owl#AcademicResearch" );

    public static final Resource ACADEMIC_SCIENTIFIC_ORGANISATION = M_MODEL.createResource( "https://w3id.org/dpv/dpv-owl#AcademicScientificOrganisation" );

    public static final Resource ACCESS_CONTROL_METHOD = M_MODEL.createResource( "https://w3id.org/dpv/dpv-owl#AccessControlMethod" );

    public static final Resource ACCOUNT_MANAGEMENT = M_MODEL.createResource( "https://w3id.org/dpv/dpv-owl#AccountManagement" );

    public static final Resource ACQUIRE = M_MODEL.createResource( "https://w3id.org/dpv/dpv-owl#Acquire" );

    public static final Resource ADAPT = M_MODEL.createResource( "https://w3id.org/dpv/dpv-owl#Adapt" );

    public static final Resource ADULT = M_MODEL.createResource( "https://w3id.org/dpv/dpv-owl#Adult" );

    /** <p>Advertising is a subset of Marketing. Advertising by itself does not indicate
     *  'personalisation' i.e. personalised ads.</p>
     */
    public static final Resource ADVERTISING = M_MODEL.createResource( "https://w3id.org/dpv/dpv-owl#Advertising" );

    public static final Resource ALIGN = M_MODEL.createResource( "https://w3id.org/dpv/dpv-owl#Align" );

    public static final Resource ALTER = M_MODEL.createResource( "https://w3id.org/dpv/dpv-owl#Alter" );

    public static final Resource ANALYSE = M_MODEL.createResource( "https://w3id.org/dpv/dpv-owl#Analyse" );

    public static final Resource ANONYMISE = M_MODEL.createResource( "https://w3id.org/dpv/dpv-owl#Anonymise" );

    /** <p>It is advised to carefully consider indicating data is fully or completely
     *  anonymised by determining whether the data by itself or in combination with
     *  other data can identify a person. Failing this condition, the data should
     *  be denoted as PseudoAnonymisedData. To indicate data is anonymised only for
     *  a specified entity (e.g. within an organisation), the concept AnonymisedDataWithinScope
     *  (as subclass of PseudoAnonymisedData) should be used instead of AnonymisedData.</p>
     */
    public static final Resource ANONYMISED_DATA = M_MODEL.createResource( "https://w3id.org/dpv/dpv-owl#AnonymisedData" );

    public static final Resource ANONYMIZATION = M_MODEL.createResource( "https://w3id.org/dpv/dpv-owl#Anonymization" );

    public static final Resource ASSESSMENT = M_MODEL.createResource( "https://w3id.org/dpv/dpv-owl#Assessment" );

    public static final Resource AUTHENTICATION_PROTOCOLS = M_MODEL.createResource( "https://w3id.org/dpv/dpv-owl#AuthenticationProtocols" );

    /** <p>non-technical authorisation procedures: How is it described on an organisational
     *  level, who gets access to the data</p>
     */
    public static final Resource AUTHORISATION_PROCEDURE = M_MODEL.createResource( "https://w3id.org/dpv/dpv-owl#AuthorisationProcedure" );

    public static final Resource AUTHORITY = M_MODEL.createResource( "https://w3id.org/dpv/dpv-owl#Authority" );

    public static final Resource CERTIFICATION = M_MODEL.createResource( "https://w3id.org/dpv/dpv-owl#Certification" );

    public static final Resource CERTIFICATION_SEAL = M_MODEL.createResource( "https://w3id.org/dpv/dpv-owl#CertificationSeal" );

    /** <p>The legality of age defining a child varies by jurisdiction. In addition,
     *  'child' is distinct from a 'minor'. For example, the legal age for consumption
     *  of alcohol can be 21, which makes a person of age 20 a 'minor' in this context.
     *  In other cases, 'minor' and 'child' are used interchangeably to refer to a
     *  person below some legally defined age.</p>
     */
    public static final Resource CHILD = M_MODEL.createResource( "https://w3id.org/dpv/dpv-owl#Child" );

    public static final Resource CODE_OF_CONDUCT = M_MODEL.createResource( "https://w3id.org/dpv/dpv-owl#CodeOfConduct" );

    public static final Resource COLLECT = M_MODEL.createResource( "https://w3id.org/dpv/dpv-owl#Collect" );

    /** <p>To indicate the source of data, use the DataSource concept with the hasDataSource
     *  relation</p>
     */
    public static final Resource COLLECTED_PERSONAL_DATA = M_MODEL.createResource( "https://w3id.org/dpv/dpv-owl#CollectedPersonalData" );

    public static final Resource COMBINE = M_MODEL.createResource( "https://w3id.org/dpv/dpv-owl#Combine" );

    public static final Resource COMMERCIAL_RESEARCH = M_MODEL.createResource( "https://w3id.org/dpv/dpv-owl#CommercialResearch" );

    public static final Resource COMMUNICATION_FOR_CUSTOMER_CARE = M_MODEL.createResource( "https://w3id.org/dpv/dpv-owl#CommunicationForCustomerCare" );

    /** <p>This purpose by itself does not sufficiently and clearly indicate what the
     *  communication is about. As such, it is recommended to combine it with another
     *  purpose to indicate the application. For example, Communication of Payment.</p>
     */
    public static final Resource COMMUNICATION_MANAGEMENT = M_MODEL.createResource( "https://w3id.org/dpv/dpv-owl#CommunicationManagement" );

    public static final Resource COMPLETE_ANONYMISATION = M_MODEL.createResource( "https://w3id.org/dpv/dpv-owl#CompleteAnonymisation" );

    public static final Resource CONSENT = M_MODEL.createResource( "https://w3id.org/dpv/dpv-owl#Consent" );

    public static final Resource CONSULT = M_MODEL.createResource( "https://w3id.org/dpv/dpv-owl#Consult" );

    public static final Resource CONSULTATION = M_MODEL.createResource( "https://w3id.org/dpv/dpv-owl#Consultation" );

    public static final Resource CONSULTATION_WITH_AUTHORITY = M_MODEL.createResource( "https://w3id.org/dpv/dpv-owl#ConsultationWithAuthority" );

    public static final Resource CONTRACT = M_MODEL.createResource( "https://w3id.org/dpv/dpv-owl#Contract" );

    public static final Resource CONTRACT_PERFORMANCE = M_MODEL.createResource( "https://w3id.org/dpv/dpv-owl#ContractPerformance" );

    public static final Resource CONTRACTUAL_TERMS = M_MODEL.createResource( "https://w3id.org/dpv/dpv-owl#ContractualTerms" );

    public static final Resource CONTROLLER_PROCESSOR_AGREEMENT = M_MODEL.createResource( "https://w3id.org/dpv/dpv-owl#ControllerProcessorAgreement" );

    public static final Resource COPY = M_MODEL.createResource( "https://w3id.org/dpv/dpv-owl#Copy" );

    /** <p>The definition of country is not intended for political interpretation. DPVCG
     *  welcomes alternate definitions based in existing sources with global scope,
     *  such as UN or ISO.</p>
     */
    public static final Resource COUNTRY = M_MODEL.createResource( "https://w3id.org/dpv/dpv-owl#Country" );

    public static final Resource CREATE_EVENT_RECOMMENDATIONS = M_MODEL.createResource( "https://w3id.org/dpv/dpv-owl#CreateEventRecommendations" );

    public static final Resource CREATE_PERSONALIZED_RECOMMENDATIONS = M_MODEL.createResource( "https://w3id.org/dpv/dpv-owl#CreatePersonalizedRecommendations" );

    public static final Resource CREATE_PRODUCT_RECOMMENDATIONS = M_MODEL.createResource( "https://w3id.org/dpv/dpv-owl#CreateProductRecommendations" );

    public static final Resource CUSTOMER_CARE = M_MODEL.createResource( "https://w3id.org/dpv/dpv-owl#CustomerCare" );

    public static final Resource CUSTOMER_CLAIMS_MANAGEMENT = M_MODEL.createResource( "https://w3id.org/dpv/dpv-owl#CustomerClaimsManagement" );

    public static final Resource CUSTOMER_MANAGEMENT = M_MODEL.createResource( "https://w3id.org/dpv/dpv-owl#CustomerManagement" );

    public static final Resource CUSTOMER_ORDER_MANAGEMENT = M_MODEL.createResource( "https://w3id.org/dpv/dpv-owl#CustomerOrderManagement" );

    public static final Resource CUSTOMER_RELATIONSHIP_MANAGEMENT = M_MODEL.createResource( "https://w3id.org/dpv/dpv-owl#CustomerRelationshipManagement" );

    public static final Resource CUSTOMER_SOLVENCY_MONITORING = M_MODEL.createResource( "https://w3id.org/dpv/dpv-owl#CustomerSolvencyMonitoring" );

    /** <p>Top class: Impact Assessment, and DPIA is sub-class</p> */
    public static final Resource DPIA = M_MODEL.createResource( "https://w3id.org/dpv/dpv-owl#DPIA" );

    public static final Resource DATA = M_MODEL.createResource( "https://w3id.org/dpv/dpv-owl#Data" );

    /** <p>The terms 'Controller' is usually the more common form of indicating a Data
     *  Controller. In ISO/IEC the term 'PII Controller' is used.</p>
     */
    public static final Resource DATA_CONTROLLER = M_MODEL.createResource( "https://w3id.org/dpv/dpv-owl#DataController" );

    /** <p>The EU, in particular the EDPB, uses data exporter the context of cross-border
     *  data transfers/flows. These concepts are not bound by jurisdictional or geopolitical
     *  scopes within DPV and can thus be used for any notion of exporting</p>
     */
    public static final Resource DATA_EXPORTER = M_MODEL.createResource( "https://w3id.org/dpv/dpv-owl#DataExporter" );

    /** <p>The EU, in particular the EDPB, uses data importing the context of cross-border
     *  data transfers/flows. These concepts are not bound by jurisdictional or geopolitical
     *  scopes within DPV and can thus be used for any notion of importing</p>
     */
    public static final Resource DATA_IMPORTER = M_MODEL.createResource( "https://w3id.org/dpv/dpv-owl#DataImporter" );

    /** <p>For specific role-based data processing agreements, see concepts for Processors
     *  and JointDataController agreements.</p>
     */
    public static final Resource DATA_PROCESSING_AGREEMENT = M_MODEL.createResource( "https://w3id.org/dpv/dpv-owl#DataProcessingAgreement" );

    public static final Resource DATA_PROCESSING_RECORDS = M_MODEL.createResource( "https://w3id.org/dpv/dpv-owl#DataProcessingRecords" );

    public static final Resource DATA_PROCESSOR = M_MODEL.createResource( "https://w3id.org/dpv/dpv-owl#DataProcessor" );

    public static final Resource DATA_PROTECTION_AUTHORITY = M_MODEL.createResource( "https://w3id.org/dpv/dpv-owl#DataProtectionAuthority" );

    public static final Resource DATA_PROTECTION_OFFICER = M_MODEL.createResource( "https://w3id.org/dpv/dpv-owl#DataProtectionOfficer" );

    /** <p>sub-processor' is a commonly used term similar to 'sub-contractor' and does
     *  not have a specific legal definition</p>
     */
    public static final Resource DATA_SUB_PROCESSOR = M_MODEL.createResource( "https://w3id.org/dpv/dpv-owl#DataSubProcessor" );

    /** <p>The term 'data subject' is specific to the GDPR, but is functionally equivalent
     *  to the term 'individual' and the ISO/IEC term 'PII Principle'.</p>
     */
    public static final Resource DATA_SUBJECT = M_MODEL.createResource( "https://w3id.org/dpv/dpv-owl#DataSubject" );

    public static final Resource DATA_TRANSFER_IMPACT_ASSESSMENT = M_MODEL.createResource( "https://w3id.org/dpv/dpv-owl#DataTransferImpactAssessment" );

    public static final Resource DATA_TRANSFER_LEGAL_BASIS = M_MODEL.createResource( "https://w3id.org/dpv/dpv-owl#DataTransferLegalBasis" );

    public static final Resource DE_IDENTIFICATION = M_MODEL.createResource( "https://w3id.org/dpv/dpv-owl#DeIdentification" );

    public static final Resource DELIVERY_OF_GOODS = M_MODEL.createResource( "https://w3id.org/dpv/dpv-owl#DeliveryOfGoods" );

    public static final Resource DERIVE = M_MODEL.createResource( "https://w3id.org/dpv/dpv-owl#Derive" );

    /** <p>Derived Data is data that is obtained through processing of existing data,
     *  e.g. deriving first name from full name. To indicate data that is derived
     *  but which was not present or evident within the source data, InferredPersonalData
     *  should be used.</p>
     */
    public static final Resource DERIVED_PERSONAL_DATA = M_MODEL.createResource( "https://w3id.org/dpv/dpv-owl#DerivedPersonalData" );

    public static final Resource DESIGN_STANDARD = M_MODEL.createResource( "https://w3id.org/dpv/dpv-owl#DesignStandard" );

    public static final Resource DESTRUCT = M_MODEL.createResource( "https://w3id.org/dpv/dpv-owl#Destruct" );

    public static final Resource DIRECT_MARKETING = M_MODEL.createResource( "https://w3id.org/dpv/dpv-owl#DirectMarketing" );

    public static final Resource DISCLOSE = M_MODEL.createResource( "https://w3id.org/dpv/dpv-owl#Disclose" );

    public static final Resource DISCLOSE_BY_TRANSMISSION = M_MODEL.createResource( "https://w3id.org/dpv/dpv-owl#DiscloseByTransmission" );

    public static final Resource DISPUTE_MANAGEMENT = M_MODEL.createResource( "https://w3id.org/dpv/dpv-owl#DisputeManagement" );

    public static final Resource DISSEMINATE = M_MODEL.createResource( "https://w3id.org/dpv/dpv-owl#Disseminate" );

    public static final Resource DURATION = M_MODEL.createResource( "https://w3id.org/dpv/dpv-owl#Duration" );

    public static final Resource ECONOMIC_UNION = M_MODEL.createResource( "https://w3id.org/dpv/dpv-owl#EconomicUnion" );

    public static final Resource ENCRYPTION = M_MODEL.createResource( "https://w3id.org/dpv/dpv-owl#Encryption" );

    public static final Resource ENCRYPTION_IN_REST = M_MODEL.createResource( "https://w3id.org/dpv/dpv-owl#EncryptionInRest" );

    public static final Resource ENCRYPTION_IN_TRANSFER = M_MODEL.createResource( "https://w3id.org/dpv/dpv-owl#EncryptionInTransfer" );

    /** <p>Was previously "Access Control". Prefixed to distinguish from Technical Measure.</p> */
    public static final Resource ENFORCE_ACCESS_CONTROL = M_MODEL.createResource( "https://w3id.org/dpv/dpv-owl#EnforceAccessControl" );

    /** <p>Was previous "Security". Prefixed to distinguish from TechOrg measures.</p> */
    public static final Resource ENFORCE_SECURITY = M_MODEL.createResource( "https://w3id.org/dpv/dpv-owl#EnforceSecurity" );

    public static final Resource ENTER_INTO_CONTRACT = M_MODEL.createResource( "https://w3id.org/dpv/dpv-owl#EnterIntoContract" );

    public static final Resource ENTITY = M_MODEL.createResource( "https://w3id.org/dpv/dpv-owl#Entity" );

    public static final Resource ERASE = M_MODEL.createResource( "https://w3id.org/dpv/dpv-owl#Erase" );

    public static final Resource FOR_PROFIT_ORGANISATION = M_MODEL.createResource( "https://w3id.org/dpv/dpv-owl#ForProfitOrganisation" );

    public static final Resource FRAUD_PREVENTION_AND_DETECTION = M_MODEL.createResource( "https://w3id.org/dpv/dpv-owl#FraudPreventionAndDetection" );

    /** <p>Generated Data is used to indicate data that is produced and is not derived
     *  or inferred from other data</p>
     */
    public static final Resource GENERATED_PERSONAL_DATA = M_MODEL.createResource( "https://w3id.org/dpv/dpv-owl#GeneratedPersonalData" );

    public static final Resource GOVERNMENTAL_ORGANISATION = M_MODEL.createResource( "https://w3id.org/dpv/dpv-owl#GovernmentalOrganisation" );

    public static final Resource GUIDELINES_PRINCIPLE = M_MODEL.createResource( "https://w3id.org/dpv/dpv-owl#GuidelinesPrinciple" );

    /** <p>HR is a broad concept. Its management includes, amongst others - recruiting
     *  employees and intermediaries e.g. brokers, independent representatives; payroll
     *  administration, remunerations, commissions, and wages; and application of
     *  social legislation.</p>
     */
    public static final Resource HUMAN_RESOURCE_MANAGEMENT = M_MODEL.createResource( "https://w3id.org/dpv/dpv-owl#HumanResourceManagement" );

    public static final Resource IDENTITY_VERIFICATION = M_MODEL.createResource( "https://w3id.org/dpv/dpv-owl#IdentityVerification" );

    public static final Resource IMPACT_ASSESSMENT = M_MODEL.createResource( "https://w3id.org/dpv/dpv-owl#ImpactAssessment" );

    public static final Resource IMPROVE_EXISTING_PRODUCTS_AND_SERVICES = M_MODEL.createResource( "https://w3id.org/dpv/dpv-owl#ImproveExistingProductsAndServices" );

    public static final Resource IMPROVE_INTERNAL_CRMPROCESSES = M_MODEL.createResource( "https://w3id.org/dpv/dpv-owl#ImproveInternalCRMProcesses" );

    public static final Resource INCREASE_SERVICE_ROBUSTNESS = M_MODEL.createResource( "https://w3id.org/dpv/dpv-owl#IncreaseServiceRobustness" );

    public static final Resource INDUSTRY_CONSORTIUM = M_MODEL.createResource( "https://w3id.org/dpv/dpv-owl#IndustryConsortium" );

    /** <p>Inferred Data is derived data generated from existing data, but which did
     *  not originally exist within it, e.g. inferring demographics from browsing
     *  history.</p>
     */
    public static final Resource INFERRED_PERSONAL_DATA = M_MODEL.createResource( "https://w3id.org/dpv/dpv-owl#InferredPersonalData" );

    public static final Resource INTERNAL_RESOURCE_OPTIMISATION = M_MODEL.createResource( "https://w3id.org/dpv/dpv-owl#InternalResourceOptimisation" );

    public static final Resource INTERNATIONAL_ORGANISATION = M_MODEL.createResource( "https://w3id.org/dpv/dpv-owl#InternationalOrganisation" );

    /** <p>To indicate the membership, hasDataController may be used</p> */
    public static final Resource JOINT_DATA_CONTROLLERS = M_MODEL.createResource( "https://w3id.org/dpv/dpv-owl#JointDataControllers" );

    public static final Resource JOINT_DATA_CONTROLLERS_AGREEMENT = M_MODEL.createResource( "https://w3id.org/dpv/dpv-owl#JointDataControllersAgreement" );

    public static final Resource LEGAL_AGREEMENT = M_MODEL.createResource( "https://w3id.org/dpv/dpv-owl#LegalAgreement" );

    /** <p>Legal basis (plural: legal bases) are defined by legislations and regulations,
     *  whose applicability is usually restricted to specific jurisdictions.</p>
     */
    public static final Resource LEGAL_BASIS = M_MODEL.createResource( "https://w3id.org/dpv/dpv-owl#LegalBasis" );

    public static final Resource LEGAL_COMPLIANCE = M_MODEL.createResource( "https://w3id.org/dpv/dpv-owl#LegalCompliance" );

    public static final Resource LEGAL_ENTITY = M_MODEL.createResource( "https://w3id.org/dpv/dpv-owl#LegalEntity" );

    public static final Resource LEGAL_OBLIGATION = M_MODEL.createResource( "https://w3id.org/dpv/dpv-owl#LegalObligation" );

    public static final Resource LEGITIMATE_INTEREST = M_MODEL.createResource( "https://w3id.org/dpv/dpv-owl#LegitimateInterest" );

    public static final Resource LEGITIMATE_INTEREST_ASSESSMENT = M_MODEL.createResource( "https://w3id.org/dpv/dpv-owl#LegitimateInterestAssessment" );

    public static final Resource LEGITIMATE_INTEREST_OF_CONTROLLER = M_MODEL.createResource( "https://w3id.org/dpv/dpv-owl#LegitimateInterestOfController" );

    public static final Resource LEGITIMATE_INTEREST_OF_THIRD_PARTY = M_MODEL.createResource( "https://w3id.org/dpv/dpv-owl#LegitimateInterestOfThirdParty" );

    /** <p>Location may be geographic, physical, or virtual.</p> */
    public static final Resource LOCATION = M_MODEL.createResource( "https://w3id.org/dpv/dpv-owl#Location" );

    public static final Resource MAKE_AVAILABLE = M_MODEL.createResource( "https://w3id.org/dpv/dpv-owl#MakeAvailable" );

    /** <p>Was commercial interest, changed to consider Marketing a separate Purpose
     *  category by itself</p>
     */
    public static final Resource MARKETING = M_MODEL.createResource( "https://w3id.org/dpv/dpv-owl#Marketing" );

    public static final Resource MEMBER_PARTNER_MANAGEMENT = M_MODEL.createResource( "https://w3id.org/dpv/dpv-owl#MemberPartnerManagement" );

    public static final Resource MOVE = M_MODEL.createResource( "https://w3id.org/dpv/dpv-owl#Move" );

    public static final Resource NDA = M_MODEL.createResource( "https://w3id.org/dpv/dpv-owl#NDA" );

    public static final Resource NATIONAL_AUTHORITY = M_MODEL.createResource( "https://w3id.org/dpv/dpv-owl#NationalAuthority" );

    public static final Resource NATURAL_PERSON = M_MODEL.createResource( "https://w3id.org/dpv/dpv-owl#NaturalPerson" );

    public static final Resource NON_COMMERCIAL_RESEARCH = M_MODEL.createResource( "https://w3id.org/dpv/dpv-owl#NonCommercialResearch" );

    public static final Resource NON_GOVERNMENTAL_ORGANISATION = M_MODEL.createResource( "https://w3id.org/dpv/dpv-owl#NonGovernmentalOrganisation" );

    /** <p>The term NonPersonalData is provided to distinguish between PersonalData and
     *  other data, e.g. for indicating which data is regulated by privacy laws. To
     *  specify personal data that has been anonymised, the concept AnonymisedData
     *  should be used.</p>
     */
    public static final Resource NON_PERSONAL_DATA = M_MODEL.createResource( "https://w3id.org/dpv/dpv-owl#NonPersonalData" );

    public static final Resource NON_PROFIT_ORGANISATION = M_MODEL.createResource( "https://w3id.org/dpv/dpv-owl#NonProfitOrganisation" );

    public static final Resource NOTICE = M_MODEL.createResource( "https://w3id.org/dpv/dpv-owl#Notice" );

    public static final Resource OBTAIN = M_MODEL.createResource( "https://w3id.org/dpv/dpv-owl#Obtain" );

    public static final Resource OFFICIAL_AUTHORITY_OF_CONTROLLER = M_MODEL.createResource( "https://w3id.org/dpv/dpv-owl#OfficialAuthorityOfController" );

    public static final Resource OPTIMISATION_FOR_CONSUMER = M_MODEL.createResource( "https://w3id.org/dpv/dpv-owl#OptimisationForConsumer" );

    public static final Resource OPTIMISATION_FOR_CONTROLLER = M_MODEL.createResource( "https://w3id.org/dpv/dpv-owl#OptimisationForController" );

    public static final Resource OPTIMISE_USER_INTERFACE = M_MODEL.createResource( "https://w3id.org/dpv/dpv-owl#OptimiseUserInterface" );

    public static final Resource ORGANISATION = M_MODEL.createResource( "https://w3id.org/dpv/dpv-owl#Organisation" );

    public static final Resource ORGANISATION_COMPLIANCE_MANAGEMENT = M_MODEL.createResource( "https://w3id.org/dpv/dpv-owl#OrganisationComplianceManagement" );

    public static final Resource ORGANISATION_GOVERNANCE = M_MODEL.createResource( "https://w3id.org/dpv/dpv-owl#OrganisationGovernance" );

    public static final Resource ORGANISATION_RISK_MANAGEMENT = M_MODEL.createResource( "https://w3id.org/dpv/dpv-owl#OrganisationRiskManagement" );

    public static final Resource ORGANISATIONAL_MEASURE = M_MODEL.createResource( "https://w3id.org/dpv/dpv-owl#OrganisationalMeasure" );

    public static final Resource ORGANISE = M_MODEL.createResource( "https://w3id.org/dpv/dpv-owl#Organise" );

    public static final Resource PIA = M_MODEL.createResource( "https://w3id.org/dpv/dpv-owl#PIA" );

    public static final Resource PAYMENT = M_MODEL.createResource( "https://w3id.org/dpv/dpv-owl#Payment" );

    /** <p>This definition of personal data encompasses the concepts used in GDPR Art.4-1
     *  for 'personal data' and ISO/IEC 2700 for 'personally identifiable information
     *  (PII)'.</p>
     */
    public static final Resource PERSONAL_DATA = M_MODEL.createResource( "https://w3id.org/dpv/dpv-owl#PersonalData" );

    public static final Resource PERSONAL_DATA_HANDLING = M_MODEL.createResource( "https://w3id.org/dpv/dpv-owl#PersonalDataHandling" );

    /** <p>This term is a blanket purpose category for indicating personalisation of
     *  some other purpose, e.g. by creating a subclass of the other concept and Personalisation</p>
     */
    public static final Resource PERSONALISATION = M_MODEL.createResource( "https://w3id.org/dpv/dpv-owl#Personalisation" );

    public static final Resource PERSONALISED_ADVERTISING = M_MODEL.createResource( "https://w3id.org/dpv/dpv-owl#PersonalisedAdvertising" );

    public static final Resource PERSONALISED_BENEFITS = M_MODEL.createResource( "https://w3id.org/dpv/dpv-owl#PersonalisedBenefits" );

    public static final Resource POLICY = M_MODEL.createResource( "https://w3id.org/dpv/dpv-owl#Policy" );

    public static final Resource PRIVACY_BY_DEFAULT = M_MODEL.createResource( "https://w3id.org/dpv/dpv-owl#PrivacyByDefault" );

    public static final Resource PRIVACY_BY_DESIGN = M_MODEL.createResource( "https://w3id.org/dpv/dpv-owl#PrivacyByDesign" );

    public static final Resource PRIVACY_NOTICE = M_MODEL.createResource( "https://w3id.org/dpv/dpv-owl#PrivacyNotice" );

    public static final Resource PROCESSING = M_MODEL.createResource( "https://w3id.org/dpv/dpv-owl#Processing" );

    public static final Resource PROFILING = M_MODEL.createResource( "https://w3id.org/dpv/dpv-owl#Profiling" );

    public static final Resource PSEUDO_ANONYMISE = M_MODEL.createResource( "https://w3id.org/dpv/dpv-owl#PseudoAnonymise" );

    public static final Resource PSEUDO_ANONYMISED_DATA = M_MODEL.createResource( "https://w3id.org/dpv/dpv-owl#PseudoAnonymisedData" );

    public static final Resource PSEUDO_ANONYMIZATION = M_MODEL.createResource( "https://w3id.org/dpv/dpv-owl#PseudoAnonymization" );

    public static final Resource PUBLIC_INTEREST = M_MODEL.createResource( "https://w3id.org/dpv/dpv-owl#PublicInterest" );

    public static final Resource PUBLIC_RELATIONS = M_MODEL.createResource( "https://w3id.org/dpv/dpv-owl#PublicRelations" );

    public static final Resource PURPOSE = M_MODEL.createResource( "https://w3id.org/dpv/dpv-owl#Purpose" );

    /** <p>A recipient of personal data can be used to indicate any entity that receives
     *  personal data. This can be a Third Party, Processor (GDPR), or even a Controller.</p>
     */
    public static final Resource RECIPIENT = M_MODEL.createResource( "https://w3id.org/dpv/dpv-owl#Recipient" );

    public static final Resource RECORD = M_MODEL.createResource( "https://w3id.org/dpv/dpv-owl#Record" );

    public static final Resource RECORD_MANAGEMENT = M_MODEL.createResource( "https://w3id.org/dpv/dpv-owl#RecordManagement" );

    public static final Resource RECORDS_OF_ACTIVITIES = M_MODEL.createResource( "https://w3id.org/dpv/dpv-owl#RecordsOfActivities" );

    public static final Resource REGION = M_MODEL.createResource( "https://w3id.org/dpv/dpv-owl#Region" );

    public static final Resource REGIONAL_AUTHORITY = M_MODEL.createResource( "https://w3id.org/dpv/dpv-owl#RegionalAuthority" );

    /** <p>Tied to compliance processes and documents, decide how to specify those</p> */
    public static final Resource REGISTER_OF_PROCESSING_ACTIVITIES = M_MODEL.createResource( "https://w3id.org/dpv/dpv-owl#RegisterOfProcessingActivities" );

    public static final Resource REGISTRATION_AUTHENTICATION = M_MODEL.createResource( "https://w3id.org/dpv/dpv-owl#RegistrationAuthentication" );

    public static final Resource REGULARITY_OF_RECERTIFICATION = M_MODEL.createResource( "https://w3id.org/dpv/dpv-owl#RegularityOfRecertification" );

    public static final Resource REMOVE = M_MODEL.createResource( "https://w3id.org/dpv/dpv-owl#Remove" );

    public static final Resource REPRESENTATIVE = M_MODEL.createResource( "https://w3id.org/dpv/dpv-owl#Representative" );

    public static final Resource REQUESTED_SERVICE_PROVISION = M_MODEL.createResource( "https://w3id.org/dpv/dpv-owl#RequestedServiceProvision" );

    public static final Resource RESEARCH_AND_DEVELOPMENT = M_MODEL.createResource( "https://w3id.org/dpv/dpv-owl#ResearchAndDevelopment" );

    public static final Resource RESTRICT = M_MODEL.createResource( "https://w3id.org/dpv/dpv-owl#Restrict" );

    public static final Resource RETRIEVE = M_MODEL.createResource( "https://w3id.org/dpv/dpv-owl#Retrieve" );

    /** <p>Risks can be associated with one or more different concepts such as purpose,
     *  processing, personal data, technical or organisational measure.</p>
     */
    public static final Resource RISK = M_MODEL.createResource( "https://w3id.org/dpv/dpv-owl#Risk" );

    /** <p>Data Protection Impact Assessments as per GDPR art 35, other Privacy Impact
     *  Assessments, threat severity assessment https://www.cnil.fr/en/privacy-impact-assessment-pia</p>
     */
    public static final Resource RISK_MANAGEMENT_PROCEDURE = M_MODEL.createResource( "https://w3id.org/dpv/dpv-owl#RiskManagementProcedure" );

    /** <p>This concept is relevant given the requirement to assert safeguards in cross-border
     *  data transfers</p>
     */
    public static final Resource SAFEGUARD = M_MODEL.createResource( "https://w3id.org/dpv/dpv-owl#Safeguard" );

    public static final Resource SAFEGUARD_FOR_DATA_TRANSFER = M_MODEL.createResource( "https://w3id.org/dpv/dpv-owl#SafeguardForDataTransfer" );

    public static final Resource SEAL = M_MODEL.createResource( "https://w3id.org/dpv/dpv-owl#Seal" );

    /** <p>Sell here means exchange, submit, or provide in return for direct or indirect
     *  compensation. Was subclass of commercial interest, changed to reflect selling
     *  something</p>
     */
    public static final Resource SELL_DATA_TO_THIRD_PARTIES = M_MODEL.createResource( "https://w3id.org/dpv/dpv-owl#SellDataToThirdParties" );

    /** <p>Sell here means exchange, submit, or provide in return for direct or indirect
     *  compensation. Was subclass of commercial interest, changed to reflect selling
     *  something</p>
     */
    public static final Resource SELL_INSIGHTS_FROM_DATA = M_MODEL.createResource( "https://w3id.org/dpv/dpv-owl#SellInsightsFromData" );

    /** <p>Sell here means exchange, submit, or provide in return for direct or indirect
     *  compensation.</p>
     */
    public static final Resource SELL_PRODUCTS = M_MODEL.createResource( "https://w3id.org/dpv/dpv-owl#SellProducts" );

    /** <p>Was subclass of commercial interest, changed to reflect selling something</p> */
    public static final Resource SELL_PRODUCTS_TO_DATA_SUBJECT = M_MODEL.createResource( "https://w3id.org/dpv/dpv-owl#SellProductsToDataSubject" );

    /** <p>Sensitivity' is a matter of context, and may be defined within legal frameworks.
     *  For GDPR, Special categories of personal data are considered a subset of sensitive
     *  data. To illustrate the difference between the two, consider the situation
     *  where Location data is collected, and which is considered 'sensitive' but
     *  not 'special'. As a probable rule, sensitive data require additional considerations
     *  whereas special category data requires additional legal basis / justifications.</p>
     */
    public static final Resource SENSITIVE_PERSONAL_DATA = M_MODEL.createResource( "https://w3id.org/dpv/dpv-owl#SensitivePersonalData" );

    /** <p>Subclass of ServiceProvision since optimisation is usually considered part
     *  of providing services</p>
     */
    public static final Resource SERVICE_OPTIMIZATION = M_MODEL.createResource( "https://w3id.org/dpv/dpv-owl#ServiceOptimization" );

    /** <p>Subclass of ServiceProvision since personalisation is usually considered part
     *  of providing services</p>
     */
    public static final Resource SERVICE_PERSONALIZATION = M_MODEL.createResource( "https://w3id.org/dpv/dpv-owl#ServicePersonalization" );

    public static final Resource SERVICE_PROVISION = M_MODEL.createResource( "https://w3id.org/dpv/dpv-owl#ServiceProvision" );

    public static final Resource SERVICE_RECORD_MANAGEMENT = M_MODEL.createResource( "https://w3id.org/dpv/dpv-owl#ServiceRecordManagement" );

    /** <p>Was "UsageAnalytics", prefixed with Service to better reflect scope</p> */
    public static final Resource SERVICE_USAGE_ANALYTICS = M_MODEL.createResource( "https://w3id.org/dpv/dpv-owl#ServiceUsageAnalytics" );

    public static final Resource SHARE = M_MODEL.createResource( "https://w3id.org/dpv/dpv-owl#Share" );

    public static final Resource SINGLE_SIGN_ON = M_MODEL.createResource( "https://w3id.org/dpv/dpv-owl#SingleSignOn" );

    public static final Resource SOCIAL_MEDIA_MARKETING = M_MODEL.createResource( "https://w3id.org/dpv/dpv-owl#SocialMediaMarketing" );

    /** <p>The term 'special category' is based on GDPR Art.9, but should not be considered
     *  as exlusive to it. DPV considers all Special Categories to also be Sensitive,
     *  but whose use is either prohibited or regulated and therefore requires additional
     *  legal basis for justification.</p>
     */
    public static final Resource SPECIAL_CATEGORY_PERSONAL_DATA = M_MODEL.createResource( "https://w3id.org/dpv/dpv-owl#SpecialCategoryPersonalData" );

    public static final Resource STAFF_TRAINING = M_MODEL.createResource( "https://w3id.org/dpv/dpv-owl#StaffTraining" );

    public static final Resource STORE = M_MODEL.createResource( "https://w3id.org/dpv/dpv-owl#Store" );

    public static final Resource STRUCTURE = M_MODEL.createResource( "https://w3id.org/dpv/dpv-owl#Structure" );

    public static final Resource SUB_PROCESSOR_AGREEMENT = M_MODEL.createResource( "https://w3id.org/dpv/dpv-owl#SubProcessorAgreement" );

    public static final Resource SUPRA_NATIONAL_AUTHORITY = M_MODEL.createResource( "https://w3id.org/dpv/dpv-owl#SupraNationalAuthority" );

    public static final Resource TARGETED_ADVERTISING = M_MODEL.createResource( "https://w3id.org/dpv/dpv-owl#TargetedAdvertising" );

    public static final Resource TECHNICAL_MEASURE = M_MODEL.createResource( "https://w3id.org/dpv/dpv-owl#TechnicalMeasure" );

    public static final Resource TECHNICAL_ORGANISATIONAL_MEASURE = M_MODEL.createResource( "https://w3id.org/dpv/dpv-owl#TechnicalOrganisationalMeasure" );

    public static final Resource TECHNICAL_SERVICE_PROVISION = M_MODEL.createResource( "https://w3id.org/dpv/dpv-owl#TechnicalServiceProvision" );

    public static final Resource THIRD_COUNTRY = M_MODEL.createResource( "https://w3id.org/dpv/dpv-owl#ThirdCountry" );

    public static final Resource THIRD_PARTY = M_MODEL.createResource( "https://w3id.org/dpv/dpv-owl#ThirdParty" );

    public static final Resource THIRD_PARTY_AGREEMENT = M_MODEL.createResource( "https://w3id.org/dpv/dpv-owl#ThirdPartyAgreement" );

    public static final Resource TRANSFER = M_MODEL.createResource( "https://w3id.org/dpv/dpv-owl#Transfer" );

    public static final Resource TRANSFORM = M_MODEL.createResource( "https://w3id.org/dpv/dpv-owl#Transform" );

    public static final Resource TRANSMIT = M_MODEL.createResource( "https://w3id.org/dpv/dpv-owl#Transmit" );

    public static final Resource USE = M_MODEL.createResource( "https://w3id.org/dpv/dpv-owl#Use" );

    public static final Resource USER_INTERFACE_PERSONALISATION = M_MODEL.createResource( "https://w3id.org/dpv/dpv-owl#UserInterfacePersonalisation" );

    public static final Resource VENDOR_MANAGEMENT = M_MODEL.createResource( "https://w3id.org/dpv/dpv-owl#VendorManagement" );

    public static final Resource VENDOR_PAYMENT = M_MODEL.createResource( "https://w3id.org/dpv/dpv-owl#VendorPayment" );

    public static final Resource VENDOR_RECORDS_MANAGEMENT = M_MODEL.createResource( "https://w3id.org/dpv/dpv-owl#VendorRecordsManagement" );

    public static final Resource VENDOR_SELECTION_ASSESSMENT = M_MODEL.createResource( "https://w3id.org/dpv/dpv-owl#VendorSelectionAssessment" );

    public static final Resource VITAL_INTEREST = M_MODEL.createResource( "https://w3id.org/dpv/dpv-owl#VitalInterest" );

    public static final Resource VITAL_INTEREST_OF_DATA_SUBJECT = M_MODEL.createResource( "https://w3id.org/dpv/dpv-owl#VitalInterestOfDataSubject" );

    public static final Resource VITAL_INTEREST_OF_NATURAL_PERSON = M_MODEL.createResource( "https://w3id.org/dpv/dpv-owl#VitalInterestOfNaturalPerson" );

    /** <p>This concept denote a Data Subject or a group are vulnerable, but not what
     *  vulnerability they possess or its context. This information can be provided
     *  additionally as comments, or as separate concepts and relations. Proposals
     *  for this are welcome.</p>
     */
    public static final Resource VULNERABLE_DATA_SUBJECT = M_MODEL.createResource( "https://w3id.org/dpv/dpv-owl#VulnerableDataSubject" );

}
