package id.semantics.soya.vocab;/* CVS $Id: $ */
 
import org.apache.jena.rdf.model.*;
 
/**
 * Vocabulary definitions from ../dpvo-05-soya.ttl 
 * @author Auto-generated by schemagen on 10 Apr 2022 17:04 
 */
public class DPVO_SOYA {
    /** <p>The RDF model that holds the vocabulary terms</p> */
    private static final Model M_MODEL = ModelFactory.createDefaultModel();
    
    /** <p>The namespace of the vocabulary as a string</p> */
    public static final String NS = "https://w3id.org/soya/dpv#";
    
    /** <p>The namespace of the vocabulary as a string</p>
     * @return namespace as String
     * @see #NS */
    public static String getURI() {return NS;}
    
    /** <p>The namespace of the vocabulary as a resource</p> */
    public static final Resource NAMESPACE = M_MODEL.createResource( NS );
    
    public static final Resource ABW = M_MODEL.createResource( "https://w3id.org/soya/dpv#ABW" );
    
    public static final Resource AF = M_MODEL.createResource( "https://w3id.org/soya/dpv#AF" );
    
    public static final Resource AFG = M_MODEL.createResource( "https://w3id.org/soya/dpv#AFG" );
    
    public static final Resource AGO = M_MODEL.createResource( "https://w3id.org/soya/dpv#AGO" );
    
    public static final Resource AIA = M_MODEL.createResource( "https://w3id.org/soya/dpv#AIA" );
    
    public static final Resource ALA = M_MODEL.createResource( "https://w3id.org/soya/dpv#ALA" );
    
    public static final Resource ALB = M_MODEL.createResource( "https://w3id.org/soya/dpv#ALB" );
    
    public static final Resource AN = M_MODEL.createResource( "https://w3id.org/soya/dpv#AN" );
    
    public static final Resource AND = M_MODEL.createResource( "https://w3id.org/soya/dpv#AND" );
    
    public static final Resource ANT = M_MODEL.createResource( "https://w3id.org/soya/dpv#ANT" );
    
    public static final Resource ARE = M_MODEL.createResource( "https://w3id.org/soya/dpv#ARE" );
    
    public static final Resource ARG = M_MODEL.createResource( "https://w3id.org/soya/dpv#ARG" );
    
    public static final Resource ARM = M_MODEL.createResource( "https://w3id.org/soya/dpv#ARM" );
    
    public static final Resource AS = M_MODEL.createResource( "https://w3id.org/soya/dpv#AS" );
    
    public static final Resource ASM = M_MODEL.createResource( "https://w3id.org/soya/dpv#ASM" );
    
    public static final Resource ATA = M_MODEL.createResource( "https://w3id.org/soya/dpv#ATA" );
    
    public static final Resource ATF = M_MODEL.createResource( "https://w3id.org/soya/dpv#ATF" );
    
    public static final Resource ATG = M_MODEL.createResource( "https://w3id.org/soya/dpv#ATG" );
    
    public static final Resource AUS = M_MODEL.createResource( "https://w3id.org/soya/dpv#AUS" );
    
    public static final Resource AUT = M_MODEL.createResource( "https://w3id.org/soya/dpv#AUT" );
    
    public static final Resource AZE = M_MODEL.createResource( "https://w3id.org/soya/dpv#AZE" );
    
    public static final Resource BDI = M_MODEL.createResource( "https://w3id.org/soya/dpv#BDI" );
    
    public static final Resource BEL = M_MODEL.createResource( "https://w3id.org/soya/dpv#BEL" );
    
    public static final Resource BEN = M_MODEL.createResource( "https://w3id.org/soya/dpv#BEN" );
    
    public static final Resource BES = M_MODEL.createResource( "https://w3id.org/soya/dpv#BES" );
    
    public static final Resource BFA = M_MODEL.createResource( "https://w3id.org/soya/dpv#BFA" );
    
    public static final Resource BGD = M_MODEL.createResource( "https://w3id.org/soya/dpv#BGD" );
    
    public static final Resource BGR = M_MODEL.createResource( "https://w3id.org/soya/dpv#BGR" );
    
    public static final Resource BHR = M_MODEL.createResource( "https://w3id.org/soya/dpv#BHR" );
    
    public static final Resource BHS = M_MODEL.createResource( "https://w3id.org/soya/dpv#BHS" );
    
    public static final Resource BIH = M_MODEL.createResource( "https://w3id.org/soya/dpv#BIH" );
    
    public static final Resource BLM = M_MODEL.createResource( "https://w3id.org/soya/dpv#BLM" );
    
    public static final Resource BLR = M_MODEL.createResource( "https://w3id.org/soya/dpv#BLR" );
    
    public static final Resource BLZ = M_MODEL.createResource( "https://w3id.org/soya/dpv#BLZ" );
    
    public static final Resource BMU = M_MODEL.createResource( "https://w3id.org/soya/dpv#BMU" );
    
    public static final Resource BOL = M_MODEL.createResource( "https://w3id.org/soya/dpv#BOL" );
    
    public static final Resource BRA = M_MODEL.createResource( "https://w3id.org/soya/dpv#BRA" );
    
    public static final Resource BRB = M_MODEL.createResource( "https://w3id.org/soya/dpv#BRB" );
    
    public static final Resource BRN = M_MODEL.createResource( "https://w3id.org/soya/dpv#BRN" );
    
    public static final Resource BTN = M_MODEL.createResource( "https://w3id.org/soya/dpv#BTN" );
    
    public static final Resource BVT = M_MODEL.createResource( "https://w3id.org/soya/dpv#BVT" );
    
    public static final Resource BWA = M_MODEL.createResource( "https://w3id.org/soya/dpv#BWA" );
    
    public static final Resource CAF = M_MODEL.createResource( "https://w3id.org/soya/dpv#CAF" );
    
    public static final Resource CAN = M_MODEL.createResource( "https://w3id.org/soya/dpv#CAN" );
    
    public static final Resource CCK = M_MODEL.createResource( "https://w3id.org/soya/dpv#CCK" );
    
    public static final Resource CHE = M_MODEL.createResource( "https://w3id.org/soya/dpv#CHE" );
    
    public static final Resource CHL = M_MODEL.createResource( "https://w3id.org/soya/dpv#CHL" );
    
    public static final Resource CHN = M_MODEL.createResource( "https://w3id.org/soya/dpv#CHN" );
    
    public static final Resource CIV = M_MODEL.createResource( "https://w3id.org/soya/dpv#CIV" );
    
    public static final Resource CMR = M_MODEL.createResource( "https://w3id.org/soya/dpv#CMR" );
    
    public static final Resource COD = M_MODEL.createResource( "https://w3id.org/soya/dpv#COD" );
    
    public static final Resource COG = M_MODEL.createResource( "https://w3id.org/soya/dpv#COG" );
    
    public static final Resource COK = M_MODEL.createResource( "https://w3id.org/soya/dpv#COK" );
    
    public static final Resource COL = M_MODEL.createResource( "https://w3id.org/soya/dpv#COL" );
    
    public static final Resource COM = M_MODEL.createResource( "https://w3id.org/soya/dpv#COM" );
    
    public static final Resource CPV = M_MODEL.createResource( "https://w3id.org/soya/dpv#CPV" );
    
    public static final Resource CRI = M_MODEL.createResource( "https://w3id.org/soya/dpv#CRI" );
    
    public static final Resource CUB = M_MODEL.createResource( "https://w3id.org/soya/dpv#CUB" );
    
    public static final Resource CUW = M_MODEL.createResource( "https://w3id.org/soya/dpv#CUW" );
    
    public static final Resource CXR = M_MODEL.createResource( "https://w3id.org/soya/dpv#CXR" );
    
    public static final Resource CYM = M_MODEL.createResource( "https://w3id.org/soya/dpv#CYM" );
    
    public static final Resource CYP = M_MODEL.createResource( "https://w3id.org/soya/dpv#CYP" );
    
    public static final Resource CZE = M_MODEL.createResource( "https://w3id.org/soya/dpv#CZE" );
    
    public static final Resource DEU = M_MODEL.createResource( "https://w3id.org/soya/dpv#DEU" );
    
    public static final Resource DJI = M_MODEL.createResource( "https://w3id.org/soya/dpv#DJI" );
    
    public static final Resource DMA = M_MODEL.createResource( "https://w3id.org/soya/dpv#DMA" );
    
    public static final Resource DNK = M_MODEL.createResource( "https://w3id.org/soya/dpv#DNK" );
    
    public static final Resource DOM = M_MODEL.createResource( "https://w3id.org/soya/dpv#DOM" );
    
    public static final Resource DZA = M_MODEL.createResource( "https://w3id.org/soya/dpv#DZA" );
    
    public static final Resource ECU = M_MODEL.createResource( "https://w3id.org/soya/dpv#ECU" );
    
    public static final Resource EGY = M_MODEL.createResource( "https://w3id.org/soya/dpv#EGY" );
    
    public static final Resource ERI = M_MODEL.createResource( "https://w3id.org/soya/dpv#ERI" );
    
    public static final Resource ESH = M_MODEL.createResource( "https://w3id.org/soya/dpv#ESH" );
    
    public static final Resource ESP = M_MODEL.createResource( "https://w3id.org/soya/dpv#ESP" );
    
    public static final Resource EST = M_MODEL.createResource( "https://w3id.org/soya/dpv#EST" );
    
    public static final Resource ETH = M_MODEL.createResource( "https://w3id.org/soya/dpv#ETH" );
    
    public static final Resource EU = M_MODEL.createResource( "https://w3id.org/soya/dpv#EU" );
    
    public static final Resource EuropeanUnion = M_MODEL.createResource( "https://w3id.org/soya/dpv#EuropeanUnion" );
    
    public static final Resource FIN = M_MODEL.createResource( "https://w3id.org/soya/dpv#FIN" );
    
    public static final Resource FJI = M_MODEL.createResource( "https://w3id.org/soya/dpv#FJI" );
    
    public static final Resource FLK = M_MODEL.createResource( "https://w3id.org/soya/dpv#FLK" );
    
    public static final Resource FRA = M_MODEL.createResource( "https://w3id.org/soya/dpv#FRA" );
    
    public static final Resource FRO = M_MODEL.createResource( "https://w3id.org/soya/dpv#FRO" );
    
    public static final Resource FSM = M_MODEL.createResource( "https://w3id.org/soya/dpv#FSM" );
    
    public static final Resource GAB = M_MODEL.createResource( "https://w3id.org/soya/dpv#GAB" );
    
    public static final Resource GBR = M_MODEL.createResource( "https://w3id.org/soya/dpv#GBR" );
    
    public static final Resource GEO = M_MODEL.createResource( "https://w3id.org/soya/dpv#GEO" );
    
    public static final Resource GGY = M_MODEL.createResource( "https://w3id.org/soya/dpv#GGY" );
    
    public static final Resource GHA = M_MODEL.createResource( "https://w3id.org/soya/dpv#GHA" );
    
    public static final Resource GIB = M_MODEL.createResource( "https://w3id.org/soya/dpv#GIB" );
    
    public static final Resource GIN = M_MODEL.createResource( "https://w3id.org/soya/dpv#GIN" );
    
    public static final Resource GLP = M_MODEL.createResource( "https://w3id.org/soya/dpv#GLP" );
    
    public static final Resource GMB = M_MODEL.createResource( "https://w3id.org/soya/dpv#GMB" );
    
    public static final Resource GNB = M_MODEL.createResource( "https://w3id.org/soya/dpv#GNB" );
    
    public static final Resource GNQ = M_MODEL.createResource( "https://w3id.org/soya/dpv#GNQ" );
    
    public static final Resource GRC = M_MODEL.createResource( "https://w3id.org/soya/dpv#GRC" );
    
    public static final Resource GRD = M_MODEL.createResource( "https://w3id.org/soya/dpv#GRD" );
    
    public static final Resource GRL = M_MODEL.createResource( "https://w3id.org/soya/dpv#GRL" );
    
    public static final Resource GTM = M_MODEL.createResource( "https://w3id.org/soya/dpv#GTM" );
    
    public static final Resource GUF = M_MODEL.createResource( "https://w3id.org/soya/dpv#GUF" );
    
    public static final Resource GUM = M_MODEL.createResource( "https://w3id.org/soya/dpv#GUM" );
    
    public static final Resource GUY = M_MODEL.createResource( "https://w3id.org/soya/dpv#GUY" );
    
    public static final Resource HKG = M_MODEL.createResource( "https://w3id.org/soya/dpv#HKG" );
    
    public static final Resource HMD = M_MODEL.createResource( "https://w3id.org/soya/dpv#HMD" );
    
    public static final Resource HND = M_MODEL.createResource( "https://w3id.org/soya/dpv#HND" );
    
    public static final Resource HRV = M_MODEL.createResource( "https://w3id.org/soya/dpv#HRV" );
    
    public static final Resource HTI = M_MODEL.createResource( "https://w3id.org/soya/dpv#HTI" );
    
    public static final Resource HUN = M_MODEL.createResource( "https://w3id.org/soya/dpv#HUN" );
    
    public static final Resource IDN = M_MODEL.createResource( "https://w3id.org/soya/dpv#IDN" );
    
    public static final Resource IMN = M_MODEL.createResource( "https://w3id.org/soya/dpv#IMN" );
    
    public static final Resource IND = M_MODEL.createResource( "https://w3id.org/soya/dpv#IND" );
    
    public static final Resource IOT = M_MODEL.createResource( "https://w3id.org/soya/dpv#IOT" );
    
    public static final Resource IRL = M_MODEL.createResource( "https://w3id.org/soya/dpv#IRL" );
    
    public static final Resource IRN = M_MODEL.createResource( "https://w3id.org/soya/dpv#IRN" );
    
    public static final Resource IRQ = M_MODEL.createResource( "https://w3id.org/soya/dpv#IRQ" );
    
    public static final Resource ISL = M_MODEL.createResource( "https://w3id.org/soya/dpv#ISL" );
    
    public static final Resource ISR = M_MODEL.createResource( "https://w3id.org/soya/dpv#ISR" );
    
    public static final Resource ITA = M_MODEL.createResource( "https://w3id.org/soya/dpv#ITA" );
    
    public static final Resource JAM = M_MODEL.createResource( "https://w3id.org/soya/dpv#JAM" );
    
    public static final Resource JEY = M_MODEL.createResource( "https://w3id.org/soya/dpv#JEY" );
    
    public static final Resource JOR = M_MODEL.createResource( "https://w3id.org/soya/dpv#JOR" );
    
    public static final Resource JPN = M_MODEL.createResource( "https://w3id.org/soya/dpv#JPN" );
    
    public static final Resource KAZ = M_MODEL.createResource( "https://w3id.org/soya/dpv#KAZ" );
    
    public static final Resource KEN = M_MODEL.createResource( "https://w3id.org/soya/dpv#KEN" );
    
    public static final Resource KGZ = M_MODEL.createResource( "https://w3id.org/soya/dpv#KGZ" );
    
    public static final Resource KHM = M_MODEL.createResource( "https://w3id.org/soya/dpv#KHM" );
    
    public static final Resource KIR = M_MODEL.createResource( "https://w3id.org/soya/dpv#KIR" );
    
    public static final Resource KNA = M_MODEL.createResource( "https://w3id.org/soya/dpv#KNA" );
    
    public static final Resource KOR = M_MODEL.createResource( "https://w3id.org/soya/dpv#KOR" );
    
    public static final Resource KWT = M_MODEL.createResource( "https://w3id.org/soya/dpv#KWT" );
    
    public static final Resource LAO = M_MODEL.createResource( "https://w3id.org/soya/dpv#LAO" );
    
    public static final Resource LBN = M_MODEL.createResource( "https://w3id.org/soya/dpv#LBN" );
    
    public static final Resource LBR = M_MODEL.createResource( "https://w3id.org/soya/dpv#LBR" );
    
    public static final Resource LBY = M_MODEL.createResource( "https://w3id.org/soya/dpv#LBY" );
    
    public static final Resource LCA = M_MODEL.createResource( "https://w3id.org/soya/dpv#LCA" );
    
    public static final Resource LIE = M_MODEL.createResource( "https://w3id.org/soya/dpv#LIE" );
    
    public static final Resource LKA = M_MODEL.createResource( "https://w3id.org/soya/dpv#LKA" );
    
    public static final Resource LSO = M_MODEL.createResource( "https://w3id.org/soya/dpv#LSO" );
    
    public static final Resource LTU = M_MODEL.createResource( "https://w3id.org/soya/dpv#LTU" );
    
    public static final Resource LUX = M_MODEL.createResource( "https://w3id.org/soya/dpv#LUX" );
    
    public static final Resource LVA = M_MODEL.createResource( "https://w3id.org/soya/dpv#LVA" );
    
    public static final Resource MAC = M_MODEL.createResource( "https://w3id.org/soya/dpv#MAC" );
    
    public static final Resource MAF = M_MODEL.createResource( "https://w3id.org/soya/dpv#MAF" );
    
    public static final Resource MAR = M_MODEL.createResource( "https://w3id.org/soya/dpv#MAR" );
    
    public static final Resource MCO = M_MODEL.createResource( "https://w3id.org/soya/dpv#MCO" );
    
    public static final Resource MDA = M_MODEL.createResource( "https://w3id.org/soya/dpv#MDA" );
    
    public static final Resource MDG = M_MODEL.createResource( "https://w3id.org/soya/dpv#MDG" );
    
    public static final Resource MDV = M_MODEL.createResource( "https://w3id.org/soya/dpv#MDV" );
    
    public static final Resource MEX = M_MODEL.createResource( "https://w3id.org/soya/dpv#MEX" );
    
    public static final Resource MHL = M_MODEL.createResource( "https://w3id.org/soya/dpv#MHL" );
    
    public static final Resource MKD = M_MODEL.createResource( "https://w3id.org/soya/dpv#MKD" );
    
    public static final Resource MLI = M_MODEL.createResource( "https://w3id.org/soya/dpv#MLI" );
    
    public static final Resource MLT = M_MODEL.createResource( "https://w3id.org/soya/dpv#MLT" );
    
    public static final Resource MMR = M_MODEL.createResource( "https://w3id.org/soya/dpv#MMR" );
    
    public static final Resource MNE = M_MODEL.createResource( "https://w3id.org/soya/dpv#MNE" );
    
    public static final Resource MNG = M_MODEL.createResource( "https://w3id.org/soya/dpv#MNG" );
    
    public static final Resource MNP = M_MODEL.createResource( "https://w3id.org/soya/dpv#MNP" );
    
    public static final Resource MOZ = M_MODEL.createResource( "https://w3id.org/soya/dpv#MOZ" );
    
    public static final Resource MRT = M_MODEL.createResource( "https://w3id.org/soya/dpv#MRT" );
    
    public static final Resource MSR = M_MODEL.createResource( "https://w3id.org/soya/dpv#MSR" );
    
    public static final Resource MTQ = M_MODEL.createResource( "https://w3id.org/soya/dpv#MTQ" );
    
    public static final Resource MUS = M_MODEL.createResource( "https://w3id.org/soya/dpv#MUS" );
    
    public static final Resource MWI = M_MODEL.createResource( "https://w3id.org/soya/dpv#MWI" );
    
    public static final Resource MYS = M_MODEL.createResource( "https://w3id.org/soya/dpv#MYS" );
    
    public static final Resource MYT = M_MODEL.createResource( "https://w3id.org/soya/dpv#MYT" );
    
    public static final Resource NA = M_MODEL.createResource( "https://w3id.org/soya/dpv#NA" );
    
    public static final Resource NAM = M_MODEL.createResource( "https://w3id.org/soya/dpv#NAM" );
    
    public static final Resource NCL = M_MODEL.createResource( "https://w3id.org/soya/dpv#NCL" );
    
    public static final Resource NER = M_MODEL.createResource( "https://w3id.org/soya/dpv#NER" );
    
    public static final Resource NFK = M_MODEL.createResource( "https://w3id.org/soya/dpv#NFK" );
    
    public static final Resource NGA = M_MODEL.createResource( "https://w3id.org/soya/dpv#NGA" );
    
    public static final Resource NIC = M_MODEL.createResource( "https://w3id.org/soya/dpv#NIC" );
    
    public static final Resource NIU = M_MODEL.createResource( "https://w3id.org/soya/dpv#NIU" );
    
    public static final Resource NLD = M_MODEL.createResource( "https://w3id.org/soya/dpv#NLD" );
    
    public static final Resource NOR = M_MODEL.createResource( "https://w3id.org/soya/dpv#NOR" );
    
    public static final Resource NPL = M_MODEL.createResource( "https://w3id.org/soya/dpv#NPL" );
    
    public static final Resource NRU = M_MODEL.createResource( "https://w3id.org/soya/dpv#NRU" );
    
    public static final Resource NZL = M_MODEL.createResource( "https://w3id.org/soya/dpv#NZL" );
    
    public static final Resource OC = M_MODEL.createResource( "https://w3id.org/soya/dpv#OC" );
    
    public static final Resource OMN = M_MODEL.createResource( "https://w3id.org/soya/dpv#OMN" );
    
    public static final Resource PAK = M_MODEL.createResource( "https://w3id.org/soya/dpv#PAK" );
    
    public static final Resource PAN = M_MODEL.createResource( "https://w3id.org/soya/dpv#PAN" );
    
    public static final Resource PCN = M_MODEL.createResource( "https://w3id.org/soya/dpv#PCN" );
    
    public static final Resource PER = M_MODEL.createResource( "https://w3id.org/soya/dpv#PER" );
    
    public static final Resource PHL = M_MODEL.createResource( "https://w3id.org/soya/dpv#PHL" );
    
    public static final Resource PLW = M_MODEL.createResource( "https://w3id.org/soya/dpv#PLW" );
    
    public static final Resource PNG = M_MODEL.createResource( "https://w3id.org/soya/dpv#PNG" );
    
    public static final Resource POL = M_MODEL.createResource( "https://w3id.org/soya/dpv#POL" );
    
    public static final Resource PRI = M_MODEL.createResource( "https://w3id.org/soya/dpv#PRI" );
    
    public static final Resource PRK = M_MODEL.createResource( "https://w3id.org/soya/dpv#PRK" );
    
    public static final Resource PRT = M_MODEL.createResource( "https://w3id.org/soya/dpv#PRT" );
    
    public static final Resource PRY = M_MODEL.createResource( "https://w3id.org/soya/dpv#PRY" );
    
    public static final Resource PSE = M_MODEL.createResource( "https://w3id.org/soya/dpv#PSE" );
    
    public static final Resource PYF = M_MODEL.createResource( "https://w3id.org/soya/dpv#PYF" );
    
    public static final Resource QAT = M_MODEL.createResource( "https://w3id.org/soya/dpv#QAT" );
    
    public static final Resource REU = M_MODEL.createResource( "https://w3id.org/soya/dpv#REU" );
    
    public static final Resource ROU = M_MODEL.createResource( "https://w3id.org/soya/dpv#ROU" );
    
    public static final Resource RUS = M_MODEL.createResource( "https://w3id.org/soya/dpv#RUS" );
    
    public static final Resource RWA = M_MODEL.createResource( "https://w3id.org/soya/dpv#RWA" );
    
    public static final Resource SA = M_MODEL.createResource( "https://w3id.org/soya/dpv#SA" );
    
    public static final Resource SAU = M_MODEL.createResource( "https://w3id.org/soya/dpv#SAU" );
    
    public static final Resource SCG = M_MODEL.createResource( "https://w3id.org/soya/dpv#SCG" );
    
    public static final Resource SDN = M_MODEL.createResource( "https://w3id.org/soya/dpv#SDN" );
    
    public static final Resource SEN = M_MODEL.createResource( "https://w3id.org/soya/dpv#SEN" );
    
    public static final Resource SGP = M_MODEL.createResource( "https://w3id.org/soya/dpv#SGP" );
    
    public static final Resource SGS = M_MODEL.createResource( "https://w3id.org/soya/dpv#SGS" );
    
    public static final Resource SHN = M_MODEL.createResource( "https://w3id.org/soya/dpv#SHN" );
    
    public static final Resource SJM = M_MODEL.createResource( "https://w3id.org/soya/dpv#SJM" );
    
    public static final Resource SLB = M_MODEL.createResource( "https://w3id.org/soya/dpv#SLB" );
    
    public static final Resource SLE = M_MODEL.createResource( "https://w3id.org/soya/dpv#SLE" );
    
    public static final Resource SLV = M_MODEL.createResource( "https://w3id.org/soya/dpv#SLV" );
    
    public static final Resource SMR = M_MODEL.createResource( "https://w3id.org/soya/dpv#SMR" );
    
    public static final Resource SOM = M_MODEL.createResource( "https://w3id.org/soya/dpv#SOM" );
    
    public static final Resource SPM = M_MODEL.createResource( "https://w3id.org/soya/dpv#SPM" );
    
    public static final Resource SRB = M_MODEL.createResource( "https://w3id.org/soya/dpv#SRB" );
    
    public static final Resource SSD = M_MODEL.createResource( "https://w3id.org/soya/dpv#SSD" );
    
    public static final Resource STP = M_MODEL.createResource( "https://w3id.org/soya/dpv#STP" );
    
    public static final Resource SUR = M_MODEL.createResource( "https://w3id.org/soya/dpv#SUR" );
    
    public static final Resource SVK = M_MODEL.createResource( "https://w3id.org/soya/dpv#SVK" );
    
    public static final Resource SVN = M_MODEL.createResource( "https://w3id.org/soya/dpv#SVN" );
    
    public static final Resource SWE = M_MODEL.createResource( "https://w3id.org/soya/dpv#SWE" );
    
    public static final Resource SWZ = M_MODEL.createResource( "https://w3id.org/soya/dpv#SWZ" );
    
    public static final Resource SXM = M_MODEL.createResource( "https://w3id.org/soya/dpv#SXM" );
    
    public static final Resource SYC = M_MODEL.createResource( "https://w3id.org/soya/dpv#SYC" );
    
    public static final Resource SYR = M_MODEL.createResource( "https://w3id.org/soya/dpv#SYR" );
    
    public static final Resource TCA = M_MODEL.createResource( "https://w3id.org/soya/dpv#TCA" );
    
    public static final Resource TCD = M_MODEL.createResource( "https://w3id.org/soya/dpv#TCD" );
    
    public static final Resource TGO = M_MODEL.createResource( "https://w3id.org/soya/dpv#TGO" );
    
    public static final Resource THA = M_MODEL.createResource( "https://w3id.org/soya/dpv#THA" );
    
    public static final Resource TJK = M_MODEL.createResource( "https://w3id.org/soya/dpv#TJK" );
    
    public static final Resource TKL = M_MODEL.createResource( "https://w3id.org/soya/dpv#TKL" );
    
    public static final Resource TKM = M_MODEL.createResource( "https://w3id.org/soya/dpv#TKM" );
    
    public static final Resource TLS = M_MODEL.createResource( "https://w3id.org/soya/dpv#TLS" );
    
    public static final Resource TON = M_MODEL.createResource( "https://w3id.org/soya/dpv#TON" );
    
    public static final Resource TTO = M_MODEL.createResource( "https://w3id.org/soya/dpv#TTO" );
    
    public static final Resource TUN = M_MODEL.createResource( "https://w3id.org/soya/dpv#TUN" );
    
    public static final Resource TUR = M_MODEL.createResource( "https://w3id.org/soya/dpv#TUR" );
    
    public static final Resource TUV = M_MODEL.createResource( "https://w3id.org/soya/dpv#TUV" );
    
    public static final Resource TWN = M_MODEL.createResource( "https://w3id.org/soya/dpv#TWN" );
    
    public static final Resource TZA = M_MODEL.createResource( "https://w3id.org/soya/dpv#TZA" );
    
    public static final Resource UGA = M_MODEL.createResource( "https://w3id.org/soya/dpv#UGA" );
    
    public static final Resource UKR = M_MODEL.createResource( "https://w3id.org/soya/dpv#UKR" );
    
    public static final Resource UMI = M_MODEL.createResource( "https://w3id.org/soya/dpv#UMI" );
    
    public static final Resource URY = M_MODEL.createResource( "https://w3id.org/soya/dpv#URY" );
    
    public static final Resource USA = M_MODEL.createResource( "https://w3id.org/soya/dpv#USA" );
    
    public static final Resource UZB = M_MODEL.createResource( "https://w3id.org/soya/dpv#UZB" );
    
    public static final Resource VAT = M_MODEL.createResource( "https://w3id.org/soya/dpv#VAT" );
    
    public static final Resource VCT = M_MODEL.createResource( "https://w3id.org/soya/dpv#VCT" );
    
    public static final Resource VEN = M_MODEL.createResource( "https://w3id.org/soya/dpv#VEN" );
    
    public static final Resource VGB = M_MODEL.createResource( "https://w3id.org/soya/dpv#VGB" );
    
    public static final Resource VIR = M_MODEL.createResource( "https://w3id.org/soya/dpv#VIR" );
    
    public static final Resource VNM = M_MODEL.createResource( "https://w3id.org/soya/dpv#VNM" );
    
    public static final Resource VUT = M_MODEL.createResource( "https://w3id.org/soya/dpv#VUT" );
    
    public static final Resource WLF = M_MODEL.createResource( "https://w3id.org/soya/dpv#WLF" );
    
    public static final Resource WSM = M_MODEL.createResource( "https://w3id.org/soya/dpv#WSM" );
    
    public static final Resource XKX = M_MODEL.createResource( "https://w3id.org/soya/dpv#XKX" );
    
    public static final Resource YEM = M_MODEL.createResource( "https://w3id.org/soya/dpv#YEM" );
    
    public static final Resource ZAF = M_MODEL.createResource( "https://w3id.org/soya/dpv#ZAF" );
    
    public static final Resource ZMB = M_MODEL.createResource( "https://w3id.org/soya/dpv#ZMB" );
    
    public static final Resource ZWE = M_MODEL.createResource( "https://w3id.org/soya/dpv#ZWE" );
    
}
